### ISSUE TITLE
Screen Lock logo

### ISSUE THREAD

**Issue by brickviking** [brickviking/night-hawk#13]
After being asked to draw up a screen lock logo, I came up with an idea that uses the same font as nighthawk does, so here's a patch for opengl.c to use instead of the bitmap. I also changed its location so it's more out of the way of gameplay, and it's up beside the score instead.

```
--- nighthawk-4.0/src/opengl.c~	2020-10-15 12:09:43.000000001 +1300
+++ nighthawk-4.0/src/opengl.c	2020-10-16 17:29:44.313147659 +1300
@@ -804,7 +804,8 @@
 static void draw_h(void)
 {
 	static char	str[STR_LABEL_LEN + 1],
-			*mess = "You cheat!";
+			*mess = "You cheat!",
+      *game_win_lock = "M LCK";
 	static int	frame_count;
 
 	if (halt_game_f == TRUE)
@@ -861,8 +862,9 @@
 		print_str(mess, 120, SCREEN_SIZE_Y - (FONT_SIZE_X + 2));
 	}
 	if (mouse_grabber_f == TRUE) {
-		glColor4f(1.0, 1.0, 0.0, 0.3);
-		blit_bm(&mouse_grabber_bm, 1, 200 - 33);
+		glColor4f(0.0, 1.0, 0.0, 0.3);
+/*		blit_bm(&mouse_grabber_bm, 1, 200 -33); *//* ECG: 16 Oct 2020 */
+		print_str(game_win_lock, 80, 0);
 	}
 
 	glDisable(GL_TEXTURE_2D);
```

**Comment by brickviking** [comment]
I thought I'd add a pretty image to show what I mean with the new shiny logo:

![small_m_lck](https://user-images.githubusercontent.com/62885/96320998-86ddda80-1070-11eb-9e0b-4f1eed21a568.png)


If necessary, we could bump up the gamma slightly, but I think it's actually a good contrast level.

**Comment by jsno8192** [comment]
Ok I'll put it in, but this will be the very last code change I do for 4.0 as the code is being frozen. After this, any new features will have to wait for a future version.

Regarding testing. All going well. I have completed all levels. I am doing it again. However, I did do some bug fixes yesterday with the door collision detection code.

**Comment by jsno8192** [comment]
RIP "Eric the mouse" logo. I thought he was good :)

**Comment by jsno8192** [comment]
That change is done. I changed game_win_lock to mess_mouse_grabber to the flag matches the message.
