### ISSUE TITLE
OpenGL bug

### ISSUE THREAD

**Issue by jsno8192** [brickviking/night-hawk#2]
The top 1/5th of the screen (nighthawk game screen) seems to update at a different time/rate than the other areas of the screen. This causes an artefact. Nb/ This is very noticeable during the noise rendering after dieing.

**Comment by brickviking** [comment]
You've got better eyesight than I have then, I hadn't noticed that one.

**Comment by jsno8192** [comment]
The above issue only occurs on my HP 15-AC168TX notebook running Mint Linux 19. I ran Nighthawk on a ASUS X415C notebook running Ubuntu 20.04, and has no issue.
