### ISSUE TITLE
Uncommanded droid movement when mouse pointer accidently moved off window

### ISSUE THREAD

**Issue by jsno8192** [brickviking/night-hawk#4]
When mouse accidentally moves off window and then clicked the xterm window behind it.  The game lost focus and the paranoid kept on wanting to move to the right. When I focused the game window again, No matter what I could do, paradroid moved right with no input.

**Comment by brickviking** [comment]
One possible fix is: whatever direction the droid is moving, hit that same key again, so the UP_KEY registers again.

**Comment by jsno8192** [comment]
Fixed. (a very simple fix too).
